# Generated by Django 5.1.4 on 2026-09-30 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('tag', models.CharField(max_length=5)),
                ('region', models.CharField(choices=[('EUW', 'EUW'), ('EUNE', 'EUNE'), ('NA', 'NA'), ('KR', 'KR'), ('BR', 'BR'), ('LAN', 'LAN'), ('LAS', 'LAS'), ('OCE', 'OCE'), ('TR', 'TR'), ('JP', 'JP')], default='EUW', max_length=5)),
                ('tier', models.CharField(choices=[('ACADEMY', 'Academy'), ('AMATEUR', 'Amateur'), ('SEMI_PRO', 'Semi Pro'), ('PRO', 'Pro')], default='AMATEUR', max_length=10)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_in_team', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'Adc'), ('SUPPORT', 'Support'), ('COACH', 'Coach'), ('ANALYST', 'Analyst'), ('SUB', 'Sub')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
            ],
            options={
                'ordering': ['role_in_team'],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
