# Generated by Django 5.1.4 on 2026-09-30 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=40, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=80)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('role', models.CharField(choices=[('TOP', 'TOP'), ('JUNGLE', 'JUNGLE'), ('MID', 'MID'), ('ADC', 'ADC'), ('SUPPORT', 'SUPPORT')], max_length=10)),
                ('region', models.CharField(choices=[('EUW', 'EUW'), ('EUNE', 'EUNE'), ('NA', 'NA'), ('KR', 'KR'), ('BR', 'BR'), ('LAN', 'LAN'), ('LAS', 'LAS'), ('OCE', 'OCE'), ('TR', 'TR'), ('JP', 'JP')], default='EUW', max_length=5)),
                ('rank', models.CharField(default='GOLD_4', max_length=20)),
                ('rank_score', models.PositiveIntegerField(default=0, editable=False)),
                ('champion_pool', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('looking_for_team', models.BooleanField(default=False)),
                ('riot_puuid', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rank_score', 'nickname'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.PositiveIntegerField(default=0)),
                ('winrate', models.FloatField(default=0, help_text='%')),
                ('kda', models.FloatField(default=0)),
                ('cs_per_min', models.FloatField(default=0)),
                ('gold_per_min', models.FloatField(default=0)),
                ('damage_share', models.FloatField(default=0, help_text='%')),
                ('vision_score_per_min', models.FloatField(default=0)),
                ('kill_participation', models.FloatField(default=0, help_text='%')),
                ('first_blood_rate', models.FloatField(default=0, help_text='%')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='scouting.playercard')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('chat_open', models.BooleanField(default=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_matches', to='scouting.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scout_matches', to='teams.team')),
            ],
            options={
                'ordering': ['-matched_at'],
                'unique_together': {('team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='ScoutMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=2000)),
                ('scout_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='scouting.scoutmatch')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSwipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('LIKE', 'Like'), ('PASS', 'Pass')], max_length=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='scouting.playercard')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_swipes', to='teams.team')),
            ],
            options={
                'unique_together': {('player', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('LIKE', 'Like'), ('PASS', 'Pass')], max_length=4)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_swipes', to='scouting.playercard')),
                ('swiper_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='teams.team')),
            ],
            options={
                'unique_together': {('swiper_team', 'player')},
            },
        ),
    ]
