# Generated by Django 5.1.4 on 2026-09-30 10:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('VOD_SUMMARY', 'Vod Summary'), ('SCOUT_SUMMARY', 'Scout Summary'), ('DRAFT_ADVICE', 'Draft Advice'), ('AGENT_CHAT', 'Agent Chat')], max_length=15)),
                ('input_ref', models.JSONField(default=dict)),
                ('output', models.TextField()),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=80)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
