# Generated by Django 5.1.4 on 2026-09-30 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=lunedì … 6=domenica')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/Rome', max_length=40)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='teams.team')),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScrimRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('BO1', 'BO1'), ('BO2', 'BO2'), ('BO3', 'BO3'), ('BO5', 'BO5')], default='BO3', max_length=3)),
                ('desired_tier', models.CharField(blank=True, choices=[('ACADEMY', 'Academy'), ('AMATEUR', 'Amateur'), ('SEMI_PRO', 'Semi Pro'), ('PRO', 'Pro')], max_length=10)),
                ('min_rank_score', models.PositiveIntegerField(default=0)),
                ('max_rank_score', models.PositiveIntegerField(default=3000)),
                ('preferred_start', models.DateTimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrim_requests', to='teams.team')),
            ],
            options={
                'ordering': ['preferred_start'],
            },
        ),
        migrations.CreateModel(
            name='Scrim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('BO1', 'BO1'), ('BO2', 'BO2'), ('BO3', 'BO3'), ('BO5', 'BO5')], default='BO3', max_length=3)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PLAYED', 'Played'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('score_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrims_as_a', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrims_as_b', to='teams.team')),
                ('request_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scrims.scrimrequest')),
                ('request_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scrims.scrimrequest')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('format', models.CharField(choices=[('SINGLE_ELIM', 'Single Elim'), ('ROUND_ROBIN', 'Round Robin')], default='SINGLE_ELIM', max_length=12)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION', 'Registration'), ('RUNNING', 'Running'), ('FINISHED', 'Finished')], default='REGISTRATION', max_length=12)),
                ('max_teams', models.PositiveSmallIntegerField(default=8)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
                ('organizer_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round', models.PositiveSmallIntegerField()),
                ('position', models.PositiveSmallIntegerField()),
                ('score_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scrims.tournamentmatch')),
                ('team_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('team_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='scrims.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ['round', 'position'],
            },
        ),
        migrations.CreateModel(
            name='TournamentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.PositiveSmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scrims.tournament')),
            ],
            options={
                'ordering': ['seed'],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
